name: push-master-and-create-code-coverage-report

on:
  push:
    branches: [master]

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yml

  push-master-and-create-code-coverage-report:
    name: Push master and deploy code coverage report
    runs-on: ubuntu-latest
    steps:
      - name: Generate build ğŸ› 
        run: npm run build

      - name: Generate coverage report ğŸ“¦
        run: npm run test:coverage:push

      - name: Send coverage rapport to Coveralls ğŸš€
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
